### ISSUE TITLE
Trouble with SSL site

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1374]
Originally reported by: **ouiea (Bitbucket: [ouiea](http://bitbucket.org/ouiea), GitHub: [ouiea](http://github.com/ouiea))**

---

I'm having trouble getting SSL to work correctly in CherryPy==3.8.0

```
#!bash

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 167, in start
    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 158, in httpserver_from_self
    httpserver = _cpwsgi_server.CPWSGIServer(self)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpwsgi_server.py", line 60, in __init__
    adapter_class = wsgiserver.get_ssl_adapter_class(ssl_module)
  File "/usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2192, in get_ssl_adapter_class
    adapter = ssl_adapters[name.lower()]
AttributeError: 'tuple' object has no attribute 'lower'
```

File: /usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py

```
#!python

def get_ssl_adapter_class(name='pyopenssl'):
    """Return an SSL adapter class for the given name."""

    adapter = ssl_adapters[name.lower()]

```

Turns out the tupple passed to it is: ('pyopenssl',)
I'm in the middle of something else, so I needed something quick and dirty to solve it and this did it.

```
#!python

def get_ssl_adapter_class(name='pyopenssl'):
    """Return an SSL adapter class for the given name."""
    if isinstance(name, tuple):
        name = name[0]
    adapter = ssl_adapters[name.lower()]

```

Thanks

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1374
