### ISSUE TITLE
Cherrypy version 11.1.0 and above does not work with latest ws4py for websockets

### ISSUE THREAD

**Issue by h3llrais3r** [cherrypy/cherrypy#1676]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

I'm upgrading for version 8.1.0 to the latest version but I can't get the websockets working.
Up until version 11.0.0 the websockets are working perfectly in combination with ws4py 0.4.2.
Once I install 11.1.0 or above, the websocket fails with the following error:
![image](https://user-images.githubusercontent.com/1945295/34145878-3e2e3e76-e498-11e7-9f92-765b435baa81.png)

* **Please tell us about your environment:**

- Cheroot version: 6.0
- CherryPy version: 11.1.0
- Python version: 2.7.9
- OS: windows 8
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

There is also a stacktrace in the console:
```
2017-12-19 08:49:38,549 ERROR [19/Dec/2017:08:49:38] ENGINE AttributeError("'NoneType' object has no attribute 'recv'",)
Traceback (most recent call last):
  File "C:\Tools\GitHub\Auto-Subliminal\lib\cheroot\server.py", line 1142, in communicate
    req.parse_request()
  File "C:\Tools\GitHub\Auto-Subliminal\lib\cheroot\server.py", line 640, in parse_request
    success = self.read_request_line()
  File "C:\Tools\GitHub\Auto-Subliminal\lib\cheroot\server.py", line 678, in read_request_line
    request_line = self.rfile.readline()
  File "C:\Tools\GitHub\Auto-Subliminal\lib\cheroot\server.py", line 234, in readline
    data = self.rfile.readline(256)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\cheroot\makefile.py", line 232, in readline
    data = self.recv(self._rbufsize)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\cheroot\makefile.py", line 82, in recv
    data = self._sock.recv(size)
AttributeError: 'NoneType' object has no attribute 'recv'
```

**Comment by webknjaz** [comment]
We should ask @Lawouach to accept Lawouach/WebSocket-for-Python#236, I think. Anyway, he should be able to release a fix.

But please also note that that distribution is not being actively maintained, and he looks for maintainers.

**Comment by Lawouach** [comment]
Hey there,

Happy to merge that one. Let me have a look.

**Comment by h3llrais3r** [comment]
Thanks for the quick response guys. 
Did not see there was already a PR pending to fix this...

**Comment by Lawouach** [comment]
Somehow, I never got the message from GH for that one no. I'll have to look at my notifications.

**Comment by Lawouach** [comment]
Merged in and released.

**Comment by h3llrais3r** [comment]
With the update of ws4py 0.4.3, the latest cherrypy version is working again for websockets.
@webknjaz @Lawouach Thanks for the quick handling. 😉
