### ISSUE TITLE
ServerStateTests::test_2_KeyboardInterrupt ERROR

### ISSUE THREAD

**Issue by loqs** [cherrypy/cherrypy#1873]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
I am submitting a bug report.

**What is the current behavior?**
cherrypy/test/test_states.py::ServerStateTests::test_2_KeyboardInterrupt ERROR

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
See https://travis-ci.org/github/cherrypy/cherrypy/jobs/740938577

**What is the expected behavior?**
cherrypy passes all tests.

**Please tell us about your environment:**

- Cheroot version:  8.4.5
- CherryPy version: 18.6.0
- Python version: 3.8.6
- OS: Arch Linux

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
Bisected to https://github.com/cherrypy/cheroot/commit/27ea61b43fc89aae1e3a3ba4dcf16f41dfe651f2
```
git bisect log
git bisect start
# good: [4f3906fb40d34f4995ddd7f6662af0e010060bed] Merge PR #282 by @meaksh
git bisect good 4f3906fb40d34f4995ddd7f6662af0e010060bed
# bad: [da3ac04f1cc2e68974dd2d8f143ffecaae1a3e37] Merge PR #309 by @liamstask
git bisect bad da3ac04f1cc2e68974dd2d8f143ffecaae1a3e37
# bad: [3135db560ffa102fd75620bbda9ddef4b22a3c72] connections: convert _num_connections to property, clarify expire()
git bisect bad 3135db560ffa102fd75620bbda9ddef4b22a3c72
# bad: [d1fdf9f108abda9be8860690ca4ab3b7b40a5aa2] connections: lint
git bisect bad d1fdf9f108abda9be8860690ca4ab3b7b40a5aa2
# bad: [27ea61b43fc89aae1e3a3ba4dcf16f41dfe651f2] connections: refactor, clarify selectors use
git bisect bad 27ea61b43fc89aae1e3a3ba4dcf16f41dfe651f2
# first bad commit: [27ea61b43fc89aae1e3a3ba4dcf16f41dfe651f2] connections: refactor, clarify selectors use
```

**Comment by webknjaz** [comment]
This will probably be fixed by https://github.com/cherrypy/cheroot/pull/331 / https://github.com/cherrypy/cheroot/pull/322. Nothing to do in this repo. Thanks for the report, though!

**Comment by webknjaz** [comment]
Duplicate of https://github.com/cherrypy/cheroot/issues/328

**Comment by webknjaz** [comment]
Reopening since the fix didn't work.

**Comment by webknjaz** [comment]
@liamstask could you please look into this? It appears like it stopped working after your recent refactoring...

**Comment by liamstask** [comment]
```
for _, key in self._selector.get_map().items():
AttributeError: 'NoneType' object has no attribute 'items'
```

given this snippet from the traceback, it may be worth testing again with the latest cheroot if possible, since as of https://github.com/cherrypy/cheroot/pull/337 the result of `_selector.get_map()` is always tested for `None`.

**Comment by webknjaz** [comment]
@liamstask I think when I tested locally it was a different exception

**Comment by liamstask** [comment]
@webknjaz do you have any tips on how to reproduce? i ran locally (`cheroot==8.4.8`) and did not see any errors.

**Comment by webknjaz** [comment]
@liamstask this test is currently disabled so the STR would be:
1) Clone the CherryPy repo, cd into it.
2) Edit the test (`nvim cherrypy/test/test_states.py +/test_2_KeyboardInterrupt`) to have it actually executed — just comment out `run=False` (better yet, drop the whole xfail marker):
```diff
diff --git a/cherrypy/test/test_states.py b/cherrypy/test/test_states.py
index 7dcad91a..601514b4 100644
--- a/cherrypy/test/test_states.py
+++ b/cherrypy/test/test_states.py
@@ -164,7 +164,7 @@ class ServerStateTests(helper.CPWebCase):
 
     @pytest.mark.xfail(
         raises=KeyboardInterrupt, reason='KeyboardInterrupt #1873',
-        run=False,
+        # run=False,
     )
     def test_2_KeyboardInterrupt(self):
         # Raise a keyboard interrupt in the HTTP server's main thread.
```
3) Execute the affected test. Here's how you can instruct pytest to select only this test:
```console
$ tox -e cheroot-master -- --no-cov cherrypy/test/test_states.py::ServerStateTests::test_2_KeyboardInterrupt --full-trace -vs
```


My understanding is that previously assigning `KeyboardInterrupt` to `cheroot.server.Server.interrupt` setter used to trigger the shutdown sequence without leaking that exception back into the calling code and not it does. Looks like https://github.com/cherrypy/cheroot/commit/27ea61b43fc89aae1e3a3ba4dcf16f41dfe651f2#diff-c6dd078cdd554284798ec45114779c10824e8a6da5b1c09ddc7e5b88651b17bdR2037-R2038 is at fault.

**Comment by liamstask** [comment]
Hm, I am not sure - that logic was effectively already present at that commit, a few lines up here: https://github.com/cherrypy/cheroot/commit/27ea61b43fc89aae1e3a3ba4dcf16f41dfe651f2#diff-c6dd078cdd554284798ec45114779c10824e8a6da5b1c09ddc7e5b88651b17bdL1797-L1802

Although at that commit, I don't see how that while loop:
```python
while self.interrupt is True:
    # Wait for self.stop() to complete. See _set_interrupt.
    time.sleep(0.1)
```
would ever break if there was an interrupt, since a) `_set_interrupt()` does not exist at that commit and b) `self._interrupt` is never cleared as part of `self.stop()`. So it seems like `self.interrupt` would remain latched True, and the thread would just hang there and never get around to re-raising the interrupt.

Is it possible the change exposed this latent issue? If so, what is the desired behavior?

**Comment by webknjaz** [comment]
It was raised in a different place on the stack. Before, it was raised from `serve()` but now it's raised around `stop()`. In particular, it used to trigger `stop()` like this https://github.com/cherrypy/cheroot/blob/bee2d3b8c7110149a888d2350f42fd24881a18c7/cheroot/server.py#L1705-L1710.

I guess what we want here is to ensure that CherryPy's behavior wasn't affected by this change. And if it wasn't, then maybe correct the test case.

**Comment by liamstask** [comment]
OK - I am not sure I have enough perspective/insight to determine the appropriate change.

At the very least, from the cherrypy test case:
```
# Raise a keyboard interrupt in a page handler; on multithreaded
# servers, this should occur in one of the worker threads.
# This should raise a BadStatusLine error, since the worker
# thread will just die without writing a response.
```
seems to be inconsistent with the cheroot implementation, since the exception is propagated from the worker thread to the server here: https://github.com/cherrypy/cheroot/blob/c99085ae6b9a745663357c077e628ba8a9a6b889/cheroot/workers/threadpool.py#L139

ie, I am not sure if this is a case in which the cherrypy test is (was) depending on a bug in cheroot, or behavior/expectations had just drifted out of sync between the two, or something else.

**Comment by webknjaz** [comment]
@liamstask I think that exception used to be propagated and handled in the past but not anymore.

I've downgraded to Cheroot v8.4.3 in the test env, and the test passes:
```console
$ .tox/cheroot-master/bin/python -m pip install 'cheroot==8.4.3'
$ tox -e cheroot-master -- --no-cov cherrypy/test/test_states.py::ServerStateTests::test_2_KeyboardInterrupt --full-trace -vs
```
When I upgraded to v8.4.4 I confirm that it makes the test fail.

So I think we need to explore whatever mechanism in v8.4.3 made it work and decide if it's still sensible.

**Comment by webknjaz** [comment]
Looks like setting the interrupt backfires into the same thread from which it was set and for CherryPy test suite is the same thread where the control from of the test method resides. But the original design was for that exception to be propagated into the thread that runs Cheroot. This would kill the server along with that thread so the exception wouldn't be a part of the control flow that assigns it to the interrupt property... And in the context of this test, this would mean that server "crashes" separately, and the client sees the disconnect (which depending on the Python version may be in form of `RemoteDisconnected`): https://github.com/cherrypy/cherrypy/blob/92fa164/cherrypy/test/test_states.py#L198-L214

The test expects that the exception will get raised from Cheroot and will get handled in `engine.block()`: https://github.com/cherrypy/cherrypy/blob/92fa164/cherrypy/process/wspbus.py#L337-L341.

**Comment by liamstask** [comment]
Got it - I opened https://github.com/cherrypy/cheroot/pull/340 to revert to the previous behavior. Please let me know if you have any tips on how best to test.

**Comment by webknjaz** [comment]
@liamstask thanks! I think that checking that this CherryPy test passes with that patch should be enough. It'd probably be useful to write an equivalent regression test on the Cheroot side to prevent future surprises post-merge... I guess assigning an interrupt from any thread including the HTTP request handlers should result in the same behavior.

**Comment by webknjaz** [comment]
This should be fixed starting with Cheroot v8.5.1.
